### ISSUE TITLE
StreamingWriteHive数据写入hive中查不到

### ISSUE THREAD

**Issue by simenliuxing** [zhangjun0x01/bigdata-examples#2]
你好，我写入hive中，在hive查不到数据。请问是我哪里有什么问题吗

**Comment by zhangjun0x01** [comment]
> 你好，我写入hive中，在hive查不到数据。请问是我哪里有什么问题吗

能具体描述一下你的环境，配置等情况吗？

**Comment by simenliuxing** [comment]
非常感谢您的回复，是我自己的问题，已经解决了。：）
